create table tb_pacotes (id_pacotes int4 generated by default as identity, data_ida varchar(255), data_volta varchar(255), destino varchar(255), origem varchar(255), preco float4 not null, primary key (id_pacotes));
INSERT INTO tb_pacotes (origem, destino, preco, data_ida, data_volTa) VALUES ('São paulo', 'Rio de Janeiro', '1200', '24/03/2022', '25/04/2022');
INSERT INTO tb_pacotes (origem, destino, preco, data_ida, data_volTa) VALUES ('Bahia', 'Rio de Janeiro', '1400', '28/03/2022', '10/04/2022');
INSERT INTO tb_pacotes (origem, destino, preco, data_ida, data_volTa) VALUES ('Natal', 'Fernando de Noronha', '1800', '29/03/2022', '19/04/2022');
